[project]
name = "wedding-planner-multi-langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zill-mint", email = "zillurdeu@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=1.4.2",
    "langchain-openai>=1.6.2",
]

[project.scripts]
wedding-planner-multi-langchain = "wedding_planner_multi_langchain:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
